### ISSUE TITLE
Generate Electron Windows 32-bit builds again

### ISSUE THREAD

**Issue by SamDelgado** [ElectronForConstruct/greenworks-prebuilds#101]
All Electron 32-bit builds for > v3.1 are no longer being built but Electron did not deprecate 32-bit for Windows. OSX has been only 64-bit for awhile, and 32-bit Linux support was dropped for versions > 3.1 according to this blog post from last March https://www.electronjs.org/blog/linux-32bit-support.

**Comment by Armaldio** [comment]
Will look into that, thanks!

**Comment by TheRealDannyyy** [comment]
Just as a heads up. the release version doesn't contain a "v" before the number. Might cause some problems with automatic selection.

![image](https://user-images.githubusercontent.com/15656049/80427505-2ef7bf80-88e8-11ea-8c2e-82b828e1bcf4.png)

**Comment by SamDelgado** [comment]
Just saw the new 32-bit Windows build! Thank you!
