### ISSUE TITLE
Pre-Release Tags are unexpectedly being displayed

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#103]
**Describe the bug**
Website doesn't automatically select the latest release build based on the version number.

**Screenshots**
![image](https://user-images.githubusercontent.com/15656049/80427833-d37a0180-88e8-11ea-8830-97d731af260f.png)

**Comment by Armaldio** [comment]
It's a pre-release, it should not even appear on the website

**Comment by TheRealDannyyy** [comment]
Changed issue to take that into account instead.
