### ISSUE TITLE
builds seem to be stuck from 1 month ago

### ISSUE THREAD

**Issue by patrickklug** [ElectronForConstruct/greenworks-prebuilds#166]
Just saw that the site doesn't seem to be updated with latest builds anymore.

**Comment by Armaldio** [comment]
Fixed with 945ce718c1bb8e5d7ae127d4055e8bfa7c64584f
Seems to be working: https://travis-ci.com/github/ElectronForConstruct/greenworks-prebuilds/jobs/396602241
