### ISSUE TITLE
Test builds for functionality (automatically)

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#20]
We haven't done this yet. Gotta ask mikai on how to do this again.

**Comment by Armaldio** [comment]
Moving this issue to this repository because it's happening here.
Let's discuss on how this should work:

- If the build is not working, should it be uploaded ?

**Comment by TheRealDannyyy** [comment]
First off we have to find a reliable test using the official plugin. Mikai knows and told me but my idiot ass already forgot.

After that we can publish as usual and just take down broken builds.

**Comment by Armaldio** [comment]
👍

**Comment by TheRealDannyyy** [comment]
@MikalDev how do you test Steamworks functionality without having a game up on the store again?

**Comment by MikalDev** [comment]
Use steam app id that all own: 480.

See details on Greenworks electron QuickStart

**Comment by TheRealDannyyy** [comment]
I created a basic test project for C2. The process and how to test the features still need to be figured out.
https://github.com/ElectronForConstruct/greenworks-prebuilds-dist/tree/master/Tests

**Comment by TheRealDannyyy** [comment]
https://steamdb.info/app/480/info/

**Comment by TheRealDannyyy** [comment]
**Test project process:**
1. Download greenworks plugin (c2)
2. Download steamworks_sdk.zip
3. Copy "...redistributable_bin" content into project files
4. Copy "...public\steam\lib" content into project files
5. Copy "steam_appid.txt" file into project files
6. Export test project with NWjs
7. Download latest custom prebuilds
8. Replace official prebuilds with custom prebuilds 
9. Add test project as non-steam game
10. Run test project and check features (https://steamdb.info/app/480/info/)

**Comment by TheRealDannyyy** [comment]
@Armaldio please transfer this one again to here:
https://github.com/ElectronForConstruct/greenworks-prebuilds-dist

(Delete this comment afterwards.)

**Comment by Armaldio** [comment]
It will not work exactly like that, but don't worry 
Also, it completely belong to here, since testing will be automated during the build

**Comment by TheRealDannyyy** [comment]
How else do you plan to test it?

**Comment by Armaldio** [comment]
I can't test a real project. Builds are hapening on a server, no steam installation is possible.
The only tests I will/I can do is to test *.node addon files

**Comment by TheRealDannyyy** [comment]
The test is in order to test the node files. How are you going to test if they function right without the process I mentioned?

**Comment by TheRealDannyyy** [comment]
This is fairly urgent so you'd have to tell me your way for testing soon. Depending on what it is, I need to adjust Skymen's script accordingly

**Comment by Armaldio** [comment]
Are we talking about the same thing? 
It seems like you've made a process for an *user* to test the addon manually  
I'm talking about automatic testing while building.

What are we talking about?

**Comment by TheRealDannyyy** [comment]
I think you're confusing something. This issue is about testing prebuilds with a selected Steamworks plugin. I have no clue what you aim to test but the mentioned process would do exactly that.

**Comment by Armaldio** [comment]
Manually ?

**Comment by TheRealDannyyy** [comment]
You just said that it's not possible to automatically run tests eith Steam. How are you gonna automatically function test the prebuilds without Steam and my example project?

**Comment by Armaldio** [comment]
I can test that the addon is valid, not corupted and that node can load it
But indeed cannot test the functions of the addon itself

**Comment by TheRealDannyyy** [comment]
We've talked about this with Mikai yesterday and I'm still skeptical about it.
Are you sure this would be enough to ensure that the prebuilds are working as intended?

**Comment by Armaldio** [comment]
Can you link me to the thread if it's public?
So you don't repeat what you already said

Also, I think it's enough
Prebuilds should be compatible with with the current greenworks version and
all that can happen to be a serious error is a corrupted or incompatible
module which should filter most of the errors

Le lun. 4 nov. 2019 à 18:01, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
There is no thread, it was a Discord convo. Set everything up and we'll roll with it then. 
I'll have to create a testing project for the video regardless of the decision made in here anyway.

**Comment by MikalDev** [comment]
In my experience, this is the majority of the errors - that the node build will not load correctly into an Electron app. You would also probably want to try including the *.dlls (or *.so or *.dynlib) from the Steam SDK to see if they can be linked to during runtime also. If you can, you should be able to run to get this error when you call the Greenwork init API (without Steam running.) You can use the Electron quickstart example from the Greenworks site to get this far and check the error.

> Failed to load Greenworks:  Error: Steam initialization failed. Steam is not running.

For example, if the *.dylib are not found you will likely get an error similar to:
> Failed to load Greenworks:  Error: Greenworks.js path not found

Electron quickstart project is here:
https://github.com/greenheartgames/greenworks/blob/master/docs/build-instructions-electron.md
nwjs quickstart project is here:
https://github.com/greenheartgames/greenworks/blob/master/docs/quick-start-nwjs.md

**Comment by Armaldio** [comment]
You can link to the starting message

Le lun. 4 nov. 2019 à 18:09, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by Armaldio** [comment]
@MikalDev this is exactly what I was going to do 👍

**Comment by TheRealDannyyy** [comment]
The convo is basically the same as the summary mikai already posted. Just scroll up in general if you really want to read it for some reason.

**Comment by Armaldio** [comment]
Closing in favor of #29
