### ISSUE TITLE
Abi 87 and newer have no MacOSX builds

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#231]
**Describe the bug**
Headline.

**Comment by TheRealDannyyy** [comment]
Any reason why MacOSX is no longer being provided in abi87 and newer?
Someone's been asking me about it so I have to give an answer. @Armaldio

**Comment by Armaldio** [comment]
I've tried a big amount of combination settings and can't make it to work with the automated system 
Either I'm missing something or greenworks isn't compatible yet

**Comment by TheRealDannyyy** [comment]
You should open an issue on the greenworks repo with the build errors attached.

**Comment by Armaldio** [comment]
https://github.com/greenheartgames/greenworks/issues/289

**Comment by TheRealDannyyy** [comment]
Looks fine, thx. Closing.
