### ISSUE TITLE
Prebuilds starting from 0.42.1 don't work

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#24]
**Describe the bug**
Prebuilds starting from 0.42.1 don't load as expected and give an error message.

**To Reproduce**
Shared steps + data in private.

**Expected behavior**
No bug pls.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/15656049/68801636-c29c4300-065c-11ea-9470-2885d77ad343.png)

**Desktop (please complete the following information):**
Only tested with Windows 64bits on a Win7 PC.

**Comment by TheRealDannyyy** [comment]
Any progress on this? [Ashley released v0.42.4](https://www.scirra.com/nwjs) recently and the prebuilds are currently not supporting it.

**Comment by Armaldio** [comment]
Didn't had the time to look into it
Maybe tomorrow

**Comment by TheRealDannyyy** [comment]
Only 64bit Windows builds are working. Stable update in 2 days.

**Comment by Armaldio** [comment]
Confirmed 32bits working

To force greenworks js file to load 32bits node addon instead of 64bits on a 64bits machine, use:
![image](https://user-images.githubusercontent.com/3089715/70554858-39562e80-1b7e-11ea-8d5d-6cf056fb3ecf.png)
