### ISSUE TITLE
Step-by-step building module guide (PWA)

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#3]
Simple step by step guild for using the automated travis gl pwa.

**Comment by Armaldio** [comment]
Updated guide
https://github.com/ElectronForConstruct/greenworks-prebuilds/tree/develop#editing-the-configuration

Do you need anything else ?

**Comment by TheRealDannyyy** [comment]
I just edit and commit this for automatic builds?

**Comment by Armaldio** [comment]
Added more details
https://github.com/ElectronForConstruct/greenworks-prebuilds/tree/master#editing-build-process

**Comment by Armaldio** [comment]
Anyway, you should not have to change anything since it's already building everything

**Comment by TheRealDannyyy** [comment]
How does it know what the most recent version of NWjs is?

**Comment by Armaldio** [comment]
Data is fetch from:
https://github.com/ElectronForConstruct/greenworks-prebuilds/blob/master/index.js#L52
https://nwjs.io/versions.json

**Comment by TheRealDannyyy** [comment]
So it's automatically fetching the most recent version. Won't touch anything if that's the case.
