### ISSUE TITLE
502 Error when trying to download any prebuilt file

### ISSUE THREAD

**Issue by kaansoral** [ElectronForConstruct/greenworks-prebuilds#337]
**Describe the bug**
TypeError: regFile is not iterable
Download requests result in 502 errors

**To Reproduce**
1. Try to download anything

**Expected behavior**

**Screenshots**
<img width="1695" alt="Screen Shot 2021-06-27 at 11 50 12" src="https://user-images.githubusercontent.com/170243/123538505-e337e480-d73d-11eb-9dfb-3336bebbe7e7.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur

**Comment by Armaldio** [comment]
Can you please try to logout and login again ?

**Comment by kaansoral** [comment]
Yes, that works,thanks - my solution at the time was to use another github account after I suspected it was just me

**Comment by Armaldio** [comment]
Fixed by https://github.com/ElectronForConstruct/greenworks-prebuilds-website/commit/077ebab5d9745e04aed03280f388b606b4280a64
