### ISSUE TITLE
Update future releases to Steamworks SDK v1.46?

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#39]
I don't know how this works but it would be nice if we could update the Steamworks SDK to the latest v1.46 release. Again not sure if this would work without problems but we could try it out perhaps?

**Comment by Armaldio** [comment]
Just tried
Not working

Reference: https://travis-ci.com/ElectronForConstruct/greenworks-prebuilds/jobs/267853701#L1309

**Comment by TheRealDannyyy** [comment]
It probably requires some reference changes in the code. Maybe we can fork greenworks and do our own thing with it.

I don't know much about the C'ish langauge it uses so this is up to you.

**Comment by Armaldio** [comment]
Won't do it 
Maybe @mikal ?

**Comment by SamDelgado** [comment]
Some good news: I am successfully using the latest Steamworks SDK v1.48a with Electron v8.2.4 and your latest greenworks prebuilt binaries. Being able to use the latest Steamworks SDK is great because the Mac notarization issue was fixed. The overlay still only works on Windows (--in-process-gpu switch is required), but everything else seems to be working fine on both Windows and OSX. I haven't gotten a chance to test a Linux build yet.

**Comment by Armaldio** [comment]
What do you mean by
> I am successfully using the latest Steamworks SDK v1.48a

Isn't the addon using the SDK only ?
Because the addon is still building against 1.42 I think

**Comment by SamDelgado** [comment]
I'm not sure that the addon is actually being built against 1.42. I downloaded the v1.48a of the Steamworks SDK and added the necessary files to the `greenworks/lib` folder along with the latest prebuilt binaries and I was pleasantly surprised to discover that everything still works.

**Comment by Armaldio** [comment]
Just opened the readme and can confirml it's 1.42
![image](https://user-images.githubusercontent.com/3089715/80749231-6ce22700-8b26-11ea-9cd3-7aa5db6ed67a.png)

**Comment by SamDelgado** [comment]
I'm not sure what Steamworks SDK files are used when greenworks is being built, but we are evidently not forced to use the same version of the SDK that greenworks is built against. I simply followed the instructions at the link below using the files from v1.48a of the SDK and everything still works.

https://github.com/greenheartgames/greenworks/blob/master/docs/build-instructions-electron.md#using-prebuilt

**Comment by Armaldio** [comment]
Good to know still ;)

**Comment by Armaldio** [comment]
Support 1.5 now
