### ISSUE TITLE
Update build process to automatically rename modules

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#4]
Example:
![unknown](https://user-images.githubusercontent.com/15656049/59868310-ec448d00-9390-11e9-9252-c180425e6c74.png)

**Comment by Armaldio** [comment]
What format should the files follow ?

**Comment by TheRealDannyyy** [comment]
Like greenheartgames does it:
https://github.com/greenheartgames/greenworks/releases

**Comment by Armaldio** [comment]
@TheRealDannyyy They use fixed version in their names, In my case it's not version but ABI
Is it a problem (I will not likely change that)
There rest is ok

**Comment by TheRealDannyyy** [comment]
All release are 32bit still, so not much of a use for me. I just need to know which version of NWjs and which the node files are for.

**Comment by Armaldio** [comment]
You mean 64bit ?
`win32` doesn't mean it's 32bit

Also, currently:

![image](https://user-images.githubusercontent.com/3089715/60041384-88d19c80-96bb-11e9-8c46-c9f82ce03519.png)

**Comment by TheRealDannyyy** [comment]
How do I know what is for 32 and 64 bit?

I don't know what that NWjs version scheme is in reference to. You'd have to explain or link it.

**Comment by Armaldio** [comment]
Only 64bits
If you want 32bits, add an issue to keep track of it

I know it's a bit tedious, but NW.js doesn't provide a command line utility like electron or node.

# To find the ABI <> NW.js version:
1. Open https://nwjs.io/versions.json
2. Find your NW.js version (ex: 0.39.1)
3. Find the corresponding `node` version (in `components`) (ex: 12.3.1)
4. OPpen https://github.com/lgeiger/node-abi/blob/master/index.js#L52
5. Pick the major version of the `node` version (ex: 12.3.1 -> 12)
6. Find the corresponding ABI in the link opened previously (ex: node 12 -> ABI 72)
7. Find the corresponding release (ex: greenworks-node-webkit-v72-{OS}.node)

**Comment by TheRealDannyyy** [comment]
That's a pain, an automatic "converter" to get that info would be easier to deal with.

**Comment by Armaldio** [comment]
Not that hard, I can do it

Le lun. 24 juin 2019 à 22:34, TheRealDannyyy <notifications@github.com> a
écrit :
