### ISSUE TITLE
Request export functions: GetLobbyMemberData and SetLobbyMemberData

### ISSUE THREAD

**Issue by Gurigraphics** [ElectronForConstruct/greenworks-prebuilds#424]
The method "greenworks.setLobbyData" work only with lobby owner.
Then, it is not possible to have communication in a lobby 

There needs use these two methods:
```js
ISteamMatchmaking::GetLobbyMemberData  = greenworks.getLobbyMemberData
ISteamMatchmaking::SetLobbyMemberData = greenworks.setLobbyMemberData
```
 
Then, when other user updates the data, it can be accessed here

```js
  greenworks.on('lobby-data-update', function(m_ulSteamIDLobby, m_ulSteamIDMember, m_bSuccess ) { 
    log('lobby-data-update'); 
    log( m_ulSteamIDLobby );  //String: the Steam ID of the Lobby.
    log( m_ulSteamIDMember ); //String: Steam ID of either the member whose data changed, or the room itself.
    log( m_bSuccess );   //Boolean: whatever the lobby data was successfully changed.
  });
```
#### References: 
[https://partner.steamgames.com/doc/features/multiplayer/matchmaking](https://partner.steamgames.com/doc/features/multiplayer/matchmaking)
[https://github.com/greenheartgames/greenworks/blob/master/docs/matchmaking.md](https://github.com/greenheartgames/greenworks/blob/master/docs/matchmaking.md)
[https://github.com/greenheartgames/greenworks/blob/master/docs/events.md](https://github.com/greenheartgames/greenworks/blob/master/docs/events.md)

**Comment by Armaldio** [comment]
Hello,


This repo is only about prebuilds, sorry

Please, submit this report at: https://github.com/greenheartgames/greenworks

**Comment by Gurigraphics** [comment]
Ok. I posted it here because in that other repo the last update was in 2018. 
 And there is no none method lobby in last greenworks-v0.13.0.
