### ISSUE TITLE
32bit support

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#5]
Issue to keep track of it.

**Comment by Armaldio** [comment]
Only for nw.js builds?

Le lun. 24 juin 2019 à 22:33, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
For me, yes.

**Comment by Armaldio** [comment]
32bits builds are available for every platform, every runtime
ALso fixed some random compilation error with that change, thakns!

**Comment by TheRealDannyyy** [comment]
Thanks, looking great. Now I gotta figure out a way to test this without a game on the store.
