### ISSUE TITLE
Something has broken the automated builds

### ISSUE THREAD

**Issue by Zamiell** [ElectronForConstruct/greenworks-prebuilds#566]
Hello,

Looks like the automated releases stopped working about a month ago.

![image](https://github.com/ElectronForConstruct/greenworks-prebuilds/assets/5511220/0248577c-5feb-44b1-bfd3-f39075aed820)

Can you take a look?

**Comment by Armaldio** [comment]
Thank you for reporting this errors!

**Comment by Zamiell** [comment]
Thanks!
