### ISSUE TITLE
Can't download files

### ISSUE THREAD

**Issue by sandyspink** [ElectronForConstruct/greenworks-prebuilds#567]
When I select files to download, then click download files, the loading bar comes up but nothing happens.

**To Reproduce**
1. Select files
2. Click "download files"
3. See that nothing downloads

**Expected behavior**
The selected file(s) should download.

**Desktop (please complete the following information):**
 - OS: Chrome browser on Macbook Pro (MacOS Big Sur Version 11.2.3)

**Comment by Armaldio** [comment]
How much files are you downloading ?

Duplicate of #565 ?

**Comment by Armaldio** [comment]
Fixed by https://github.com/ElectronForConstruct/greenworks-prebuilds-website/commit/077ebab5d9745e04aed03280f388b606b4280a64
