### ISSUE TITLE
Website Out-Of-Beta Changes

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#78]
- [x] Hamburger icon missing hover feedback
- [x] Top button order change: Donations | GitHub | Share URL | Bugs
- [x] Change "version range" text to "version"
- [x] Bug fixes + changes (#92)
- [x] Change Donation link to `https://github.com/sponsors/Armaldio`
- [x] Remove Beta tag

**Comment by Armaldio** [comment]
> Only show icon for top links (optional: show text on hover)
Not ok with this
I think it's better to have it explicit

**Comment by TheRealDannyyy** [comment]
Do as you like but with the new stuff it will get cluttered and it's already almost out of space in 720p.
![image](https://user-images.githubusercontent.com/15656049/78189297-0fe54980-7472-11ea-8da7-21afd673cead.png)

**Comment by Armaldio** [comment]
I hide labels based on screen size

**Comment by TheRealDannyyy** [comment]
That's added work but up to you.

**Comment by Armaldio** [comment]
It's really [just a few characters](https://vuetifyjs.com/en/styles/display/#visibility)

**Comment by TheRealDannyyy** [comment]
As soon as the last minor issue is fixed. We can go stable and the beta tag can be removed.
