### ISSUE TITLE
[Regression] Shortened links trigger errors again

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#79]
![image](https://user-images.githubusercontent.com/15656049/73925119-d529bf80-48cd-11ea-9ea1-338d9db00632.png)

**Comment by Armaldio** [comment]
I think I will just remove the option to have short URLs
I can't make it reliable

**Comment by TheRealDannyyy** [comment]
Keep in mind that I can't use normal short url on the forum. I would have to bit.ly those then.

**Comment by Armaldio** [comment]
Ah, right
Any new solution ideas ?

**Comment by TheRealDannyyy** [comment]
Again you can leave the url sharing but only remove the short url creator. I will just shorten using bitly.

**Comment by Armaldio** [comment]
> Again you can leave the url sharing but only remove the short url creator. I will just shorten using bitly.

Of course i'll just remove the short url creator
Still searching some workarounds

**Comment by TheRealDannyyy** [comment]
Maybe check out if bitly itself has an API else it doesn't matter, as long as I can create some automatic filtering link at all.

**Comment by Armaldio** [comment]
Closing for now, have no valid solutions
