### ISSUE TITLE
Add "Revoke Access" option

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#82]
Above "Disconnect" add a "Revoke Access" button. 
Pressing this button will do the following:
- Display dialog 
(**Warning**; You are about to revoke website permissions and disconnect. Continue?; OK | Cancel)
- Revoke permission access for website
- Disconnect user

**Comment by Armaldio** [comment]
Can't do it the way you want: https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#directing-users-to-review-their-access

I'm proposing:
- Display dialog
(Warning; You are about to revoke website permissions and disconnect. Continue?; OK | Cancel)
- Logout user
- Open revoke page in new tab

**Comment by TheRealDannyyy** [comment]
Just open the revoke access page and check for if auth is necessary when downloading.
