### ISSUE TITLE
Merge website repo with greenworks-prebuilds

### ISSUE THREAD

**Issue by TheRealDannyyy** [ElectronForConstruct/greenworks-prebuilds#89]
This was a something you mentioned earlier. If this is no longer happening, please change top GitHub button to link to this repo instead of the website one (https://github.com/ElectronForConstruct/greenworks-prebuilds).

**Comment by Armaldio** [comment]
After thinking about it, it's better to keep it separated
Also, leave issues abut the website inside the website repo issues

**Comment by TheRealDannyyy** [comment]
I don't this it's a good idea and we should keep the merged issues. It just over complicates things.
