### ISSUE TITLE
Request for new release post #248 on Greenworks

### ISSUE THREAD

**Issue by MikalDev** [ElectronForConstruct/greenworks-prebuilds#9]
Please create a new release using the source post #248 from the Greenworks github.

Looking to use some of the recent new features added to the Greenworks API.

**Comment by TheRealDannyyy** [comment]
@MikalDev Do you think you could get #220 running soon as well? It's a great PR for online lobby support and more that's still in limbo.

https://github.com/greenheartgames/greenworks/pull/220

**Comment by MikalDev** [comment]
I looked at briefly, it looks like it needs some documentation updates for the PR to be accepted - I'm going to let someone else who is interested in those APIs do that work. I'm focusing more on multiplayer supporting using Playfab, not Steam.

**Comment by TheRealDannyyy** [comment]
It's not meant to be a multiplayer replacement. More a bridge to interact with Steam's "join lobby" and other interface options, which then trigger the official multiplayer plugin's features.

**Comment by MikalDev** [comment]
I'm using Playfab for those types of functions, so I'm not that interested in this API. If you want to discuss more let's take it to Discord, instead of hijacking this issue.

**Comment by TheRealDannyyy** [comment]
Just thought I can fit another PR in this.

It's alright, just want someone to finish what the Steam4C2 plugin started.
